<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IAEngineProject Condition="'$(IAEngineProject)' == ''">$(MSBuildThisFileDirectory)..\..\..\AI-ENGINEERING-ENGINE\OnlineOs.AiOrchestrator.csproj</IAEngineProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(IAEngineProject)" />
  </ItemGroup>

</Project>
